### PR TITLE
Update to set field javaAnnotations in constructor and accessors

### PR DESCRIPTION
**Pull request by ryan-barker-zefr**
This allows @ Nonnull to work properly in Kotlin

### CODE REVIEW

**Comment by ryan-barker-zefr** [comment]
This code is intentionally not fully tested so it can be submitted to apache avro for review as to implementation before writing tests.  It was manually tested with commons-avro

**Comment by Bluexin** [comment]
This can be useful, however the ticket was about using them instead of Optional (or rather an improved version only adding them when needed).

**Comment by florianmutter** [comment]
I would love to see this being completed. Is there any chance you might finish it and create a PR against apache/avro?

**Comment by daviian** [comment]
@ryan-barker-zefr I really would love to have this upstream. Is there something we can support you with?

**Comment by ryan-barker-zefr** [comment]
@florianmutter and others, I have merged to master and pulled in all changes from the source as well.

I was going to make a PR but there are many reasons it will be rejected. No JIRA issue, poor commit names, no tests. 

Please feel free to take this code and fix it up as desired. I do not have time to make this contribution officially.

**Pull request merged**
